# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-21 19:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fallowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallowed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fallowing', to=settings.AUTH_USER_MODEL, verbose_name='Takip edilen kullanıcı')),
                ('fallower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fallower', to=settings.AUTH_USER_MODEL, verbose_name='Takip eden kullanıcı')),
            ],
        ),
    ]
