# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-09 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fallowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fallowing',
            options={'verbose_name_plural': 'Takipleşme Sistemi'},
        ),
    ]
