# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-25 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='kategoriler',
            field=models.ManyToManyField(related_name='blog', to='blog.Kategori'),
        ),
    ]
