# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-26 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180826_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='unique_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
