# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-26 19:28
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blog_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='yayin_taslak',
            field=models.CharField(choices=[('yayin', 'YAYIN'), ('taslak', 'TASLAK')], default='yayin', max_length=6),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default/default-photo.jpg', help_text='Kapak Fotoğrafı Yükleyiniz', null=True, upload_to=blog.models.upload_to, verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
