# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 21:07
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180826_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='icerik',
            field=ckeditor.fields.RichTextField(max_length=5000, null=True, verbose_name='İçerik'),
        ),
    ]
