# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-21 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_favoriteblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteblog',
            options={'verbose_name_plural': 'Favorilere Eklenen Gönderiler'},
        ),
    ]
